# [ General settings ğŸ”§ ]
start-at-login = true

accordion-padding = 24

on-focused-monitor-changed = []
on-focus-changed = ['move-mouse window-lazy-center']

automatically-unhide-macos-hidden-apps = true

[gaps]
inner.horizontal = 8
inner.vertical = 8
outer.left = 16
outer.bottom = 16
outer.top = 16
outer.right = 16

# [ Key mappings ğŸ”‘ ]
[mode.main.binding]
# NOTE 1 - Available keys:
#   - Letters.        a, b, c, ..., z
#   - Numbers.        0, 1, 2, ..., 9
#   - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
#   - F-keys.         f1, f2, ..., f20
#   - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
#                     backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
#                     backspace, tab, pageUp, pageDown, home, end, forwardDelete,
#                     sectionSign (ISO keyboards only, european keyboards only)
#   - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                     keypadMinus, keypadMultiply, keypadPlus
#   - Arrows.         left, down, up, right
#   - Modifiers.      cmd, alt, ctrl, shift
# NOTE 2 - Available commands: https://nikitabobko.github.io/AeroSpace/commands

# Cycle layouts ğŸ”„
ctrl-cmd-slash = 'layout tiles horizontal vertical'
ctrl-cmd-comma = 'layout accordion horizontal vertical'

# Move/throw nodes within a space ğŸŒŒ
ctrl-cmd-h = 'focus left'
ctrl-cmd-j = 'focus down'
ctrl-cmd-k = 'focus up'
ctrl-cmd-l = 'focus right'

ctrl-alt-h = 'move left'
ctrl-alt-j = 'move down'
ctrl-alt-k = 'move up'
ctrl-alt-l = 'move right'

# Join nodes together ğŸ¤
ctrl-alt-left = 'join-with left'
ctrl-alt-down = 'join-with down'
ctrl-alt-up = 'join-with up'
ctrl-alt-right = 'join-with right'

# Resize nodes => [i]n/[o]ut ğŸ“
ctrl-cmd-i = 'resize smart -50'
ctrl-cmd-o = 'resize smart +50'

# Switch/throw to workspaces ğŸ‘¨â€ğŸ­
ctrl-cmd-1 = 'workspace 1'
ctrl-cmd-2 = 'workspace 2'
ctrl-cmd-3 = 'workspace 3'
ctrl-cmd-4 = 'workspace 4'
ctrl-cmd-5 = 'workspace 5'
ctrl-cmd-6 = 'workspace 6'
ctrl-cmd-7 = 'workspace 7'
ctrl-cmd-8 = 'workspace 8'
ctrl-cmd-9 = 'workspace 9'
ctrl-cmd-0 = 'workspace 10'

ctrl-alt-1 = 'move-node-to-workspace 1'
ctrl-alt-2 = 'move-node-to-workspace 2'
ctrl-alt-3 = 'move-node-to-workspace 3'
ctrl-alt-4 = 'move-node-to-workspace 4'
ctrl-alt-5 = 'move-node-to-workspace 5'
ctrl-alt-6 = 'move-node-to-workspace 6'
ctrl-alt-7 = 'move-node-to-workspace 7'
ctrl-alt-8 = 'move-node-to-workspace 8'
ctrl-alt-9 = 'move-node-to-workspace 9'
ctrl-alt-0 = 'move-node-to-workspace 10'

# Switch back and forth between workspaces â®ï¸
ctrl-cmd-tab = 'workspace-back-and-forth'

# Move workspace to monitor the next monitor ğŸ‘€
ctrl-alt-tab = 'move-workspace-to-monitor --wrap-around next'

# [R]eset layout ğŸ—ï¸
ctrl-cmd-r = 'flatten-workspace-tree'

# [R]eload config ğŸ§°
ctrl-alt-r = 'reload-config'

# [T]oggle between floating and tiling layout ğŸ“º
ctrl-cmd-t = 'layout floating tiling'

# Close all windows but the current one ğŸš«
ctrl-cmd-x = 'close-all-windows-but-current'
